package com.gemini.springboot.web.ext;

import com.gemini.springboot.web.dao.TcUserMapper;
import org.apache.ibatis.annotations.Mapper;

/**
 * Description: TcUserExtDao <br>
 *
 * Do not edit this file
 * It was auto-generated by Code-Generator
 *
 * @since 2019-1-6 22:23:32
 */
@Mapper
public interface TcUserExtDao extends TcUserMapper, BaseMapper {

}