package com.gemini.springboot.web.service.impl;


import com.gemini.springboot.web.ext.TcUserExtDao;
import com.gemini.springboot.web.entity.TcUser;
import com.gemini.springboot.web.service.TcUserService;
import com.gemini.springboot.web.util.PageUtil;
import org.springframework.stereotype.Service;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.annotation.Resource;
import java.util.List;

/**
 * Description: TcUserServiceImpl <br>
 *
 * Do not edit this file
 * It was auto-generated by Code-Generator
 *
 * @since 2019-1-6 22:23:31
 */
@Service
public class TcUserServiceImpl implements TcUserService {

    private static final Logger logger = LoggerFactory.getLogger(TcUserServiceImpl.class);

    @Resource
    private TcUserExtDao tcUserExtDao;

    @Override
    public int save(TcUser tcUser) {
        return tcUserExtDao.insertSelective(tcUser);
    }

    @Override
    public int update(TcUser tcUser) {
        return tcUserExtDao.updateByPrimaryKeySelective(tcUser);
    }

    @Override
    public int delete(Integer id) {
        return tcUserExtDao.deleteByPrimaryKey(id);
    }

    @Override
    public int count(TcUser tcUser){
        return tcUserExtDao.queryForCount(tcUser);
    }

    @Override
    public TcUser queryById(Integer id) {
        return tcUserExtDao.selectByPrimaryKey(id);
    }

    @Override
    public List<TcUser> queryList(TcUser tcUser) {
        return tcUserExtDao.queryForList(tcUser, null);
    }

    @Override
    public List<TcUser> queryPage(TcUser tcUser, Integer pageNum, Integer countEachPage){
        return tcUserExtDao.queryForList(tcUser, PageUtil.initPage(pageNum, countEachPage));
    }
}