package com.gemini.springboot.web.service;

import com.gemini.springboot.web.entity.TcUser;

import java.util.List;

/**
 * Description: TcUserService <br>
 *
 * Do not edit this file
 * It was auto-generated by Code-Generator
 *
 * @since 2019-1-6 22:23:31
 */
public interface TcUserService {

    /**
     * 新增
     *
     * @param tcUser
     * @return
     */
    int save(TcUser tcUser);

    /**
     * 更新操作
     *
     * @param tcUser
     * @return
     */
    int update(TcUser tcUser);

    /**
     * 物理删除操作
     *
     * @param id
     * @return
     */
    int delete(Integer id);

    /**
     * 查询数量
     *
     * @param tcUser
     * @return
     */
    int count(TcUser tcUser);

    /**
     * 根据 id 查询信息
     *
     * @param id
     * @return
     */
    TcUser queryById(Integer id);

    /**
     * 多条件查询返回集合
     *
     * @param tcUser
     * @return
     */
    List<TcUser> queryList(TcUser tcUser);

    /**
     * 分页多条件查询返回集合
     *
     * @param tcUser
     * @param pageNum
     * @param countEachPage
     * @return
     */
    List<TcUser> queryPage(TcUser tcUser, Integer pageNum, Integer countEachPage);
}